#!/usr/bin/env tsx
/**
 * Pocket-Claude setup wizard.
 * Запускается из корня репо: `pnpm setup` или `npm run setup`.
 *
 * Что делает:
 *  1. Проверяет Node 20+, Docker, pnpm/npm
 *  2. Задаёт 5 вопросов (домен, email, пароль, порт)
 *  3. Генерирует .env, docker-compose.override.yml (если нужен)
 *  4. Применяет миграции
 *  5. Показывает следующие шаги
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { execSync, spawn } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { createInterface } from 'node:readline/promises';
import { stdin, stdout } from 'node:process';

const rl = createInterface({ input: stdin, output: stdout });
const ask = (q: string, def?: string) => rl.question(def ? `${q} [${def}] ` : `${q} `);

function log(s: string) { console.log(s); }
function ok(s: string) { console.log(`\x1b[32m✓\x1b[0m ${s}`); }
function warn(s: string) { console.log(`\x1b[33m⚠\x1b[0m ${s}`); }
function die(s: string): never { console.error(`\x1b[31m✗\x1b[0m ${s}`); process.exit(1); }

async function main() {
  log('\nAutmzr Command — setup wizard\n');

  // Prerequisites
  const nodeMajor = Number(process.versions.node.split('.')[0]);
  if (nodeMajor < 20) die(`Node 20+ required (you have ${process.version})`);
  ok(`Node ${process.version}`);

  if (!existsSync('package.json')) die('Run from repo root (package.json not found)');

  // Checking .env
  if (existsSync('.env')) {
    warn('.env already exists — skipping wizard questions.');
    warn('Delete .env if you want to re-run wizard.');
  } else {
    const domain = (await ask('Публичный URL (http://localhost:3100 для dev):', 'http://localhost:3100')).trim() || 'http://localhost:3100';
    const port = (await ask('Порт мастера:', '3100')).trim() || '3100';
    const pgUrl = (await ask('DATABASE_URL:', 'postgresql://pc:pcpwd@localhost:5432/pocket_claude')).trim() || 'postgresql://pc:pcpwd@localhost:5432/pocket_claude';
    const adminEmail = (await ask('Email админа:')).trim();
    const adminPwd = (await ask('Пароль админа (6+ символов):')).trim();
    if (adminPwd.length < 6) die('Пароль слишком короткий');

    const sessionSecret = randomBytes(32).toString('hex');
    const integrationKey = randomBytes(32).toString('hex');

    const env = [
      `# Generated by setup wizard at ${new Date().toISOString()}`,
      `DATABASE_URL=${pgUrl}`,
      `SESSION_SECRET=${sessionSecret}`,
      `INTEGRATION_KEY=${integrationKey}`,
      `PORT=${port}`,
      `PUBLIC_URL=${domain}`,
      `SINGLE_USER_MODE=true`,
      `ADMIN_EMAIL=${adminEmail}`,
      `ADMIN_PASSWORD=${adminPwd}`,
      ``,
    ].join('\n');
    writeFileSync('.env', env);
    ok('.env created');
  }

  rl.close();

  log('\nNext steps:\n');
  log('  1. Start Postgres (if not running):');
  log('     docker compose up -d postgres');
  log('  2. Apply migrations:');
  log('     pnpm --filter @autmzr/command-master migrate');
  log('  3. Run master in dev:');
  log('     pnpm dev');
  log('\nThen open http://localhost:3100 and sign in.\n');
  log('To add a device, click Settings → + Device and copy the shown command.');
  log('\n');
}

main().catch((e) => { console.error(e); process.exit(1); });
